channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.8
  - pip
  - pip:
      - selenium
      - openpyxl
      - requests
  - nodejs  # Required if Selenium's WebDriver depends on Node.js
